# Generated by Django 5.1.6 on 2025-04-30 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_document', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='file_extension',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='original_filename',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
