# Generated by Django 5.1.6 on 2025-05-01 09:57

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_document', '0003_catalog_created_at_catalog_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plagiarismcheck',
            name='highlights',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, help_text='List of matched text snippets', null=True, size=None),
        ),
        migrations.AlterField(
            model_name='plagiarismcheck',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checks', to='app_document.document'),
        ),
        migrations.AlterField(
            model_name='plagiarismcheck',
            name='duplicate_sources',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
