# Generated by Django 5.1.6 on 2025-06-02 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_document', '0004_plagiarismcheck_highlights_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='publication_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
