# Generated by Django 5.1.6 on 2025-06-05 03:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_document', '0005_alter_document_publication_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='Term',
            fields=[
                ('text', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('doc_freq', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Posting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term_freq', models.IntegerField()),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postings', to='app_document.document')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postings', to='app_document.term')),
            ],
            options={
                'unique_together': {('term', 'document')},
            },
        ),
    ]
