# Generated by Django 5.1.6 on 2025-06-05 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_document', '0006_term_posting'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='doc_length',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(help_text='Tệp văn bản (txt, pdf, docx)', upload_to='documents/%Y/%m/%d/', verbose_name='Tệp văn bản'),
        ),
    ]
